name: Code Quality

on:
  push:
    branches:
      - master
      - dev
      - feature-*
      - improvement-*
      - fix-*
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@master
      - name: Node Setup
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '10.x'
      - name: Install Dev Deps
        run: cd frontend && npm install --only=dev
      - name: ESLint
        run: cd frontend && npx eslint js
